# TCL File Generated by Component Editor 18.0
# Fri Dec 08 15:20:02 MSK 2023
# DO NOT MODIFY


# 
# hdmi_st "hdmi_st" v1.0
#  2023.12.08.15:20:01
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module hdmi_st
# 
set_module_property DESCRIPTION ""
set_module_property NAME hdmi_st
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME hdmi_st
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL hdmi_st
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file hdmi_st.sv SYSTEM_VERILOG PATH hdmi_st.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL hdmi_st
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file hdmi_st.sv SYSTEM_VERILOG PATH hdmi_st.sv


# 
# parameters
# 
add_parameter horz_front_porch INTEGER 18 ""
set_parameter_property horz_front_porch DEFAULT_VALUE 18
set_parameter_property horz_front_porch DISPLAY_NAME horz_front_porch
set_parameter_property horz_front_porch TYPE INTEGER
set_parameter_property horz_front_porch UNITS None
set_parameter_property horz_front_porch ALLOWED_RANGES -2147483648:2147483647
set_parameter_property horz_front_porch DESCRIPTION ""
set_parameter_property horz_front_porch HDL_PARAMETER true
add_parameter horz_sync INTEGER 60 ""
set_parameter_property horz_sync DEFAULT_VALUE 60
set_parameter_property horz_sync DISPLAY_NAME horz_sync
set_parameter_property horz_sync TYPE INTEGER
set_parameter_property horz_sync UNITS None
set_parameter_property horz_sync ALLOWED_RANGES -2147483648:2147483647
set_parameter_property horz_sync DESCRIPTION ""
set_parameter_property horz_sync HDL_PARAMETER true
add_parameter horz_back_porch INTEGER 111 ""
set_parameter_property horz_back_porch DEFAULT_VALUE 111
set_parameter_property horz_back_porch DISPLAY_NAME horz_back_porch
set_parameter_property horz_back_porch TYPE INTEGER
set_parameter_property horz_back_porch UNITS None
set_parameter_property horz_back_porch ALLOWED_RANGES -2147483648:2147483647
set_parameter_property horz_back_porch DESCRIPTION ""
set_parameter_property horz_back_porch HDL_PARAMETER true
add_parameter horz_pix INTEGER 1024 ""
set_parameter_property horz_pix DEFAULT_VALUE 1024
set_parameter_property horz_pix DISPLAY_NAME horz_pix
set_parameter_property horz_pix TYPE INTEGER
set_parameter_property horz_pix UNITS None
set_parameter_property horz_pix ALLOWED_RANGES -2147483648:2147483647
set_parameter_property horz_pix DESCRIPTION ""
set_parameter_property horz_pix HDL_PARAMETER true
add_parameter vert_front_porch INTEGER 18 ""
set_parameter_property vert_front_porch DEFAULT_VALUE 18
set_parameter_property vert_front_porch DISPLAY_NAME vert_front_porch
set_parameter_property vert_front_porch TYPE INTEGER
set_parameter_property vert_front_porch UNITS None
set_parameter_property vert_front_porch ALLOWED_RANGES -2147483648:2147483647
set_parameter_property vert_front_porch DESCRIPTION ""
set_parameter_property vert_front_porch HDL_PARAMETER true
add_parameter vert_sync INTEGER 60 ""
set_parameter_property vert_sync DEFAULT_VALUE 60
set_parameter_property vert_sync DISPLAY_NAME vert_sync
set_parameter_property vert_sync TYPE INTEGER
set_parameter_property vert_sync UNITS None
set_parameter_property vert_sync ALLOWED_RANGES -2147483648:2147483647
set_parameter_property vert_sync DESCRIPTION ""
set_parameter_property vert_sync HDL_PARAMETER true
add_parameter vert_back_porch INTEGER 111 ""
set_parameter_property vert_back_porch DEFAULT_VALUE 111
set_parameter_property vert_back_porch DISPLAY_NAME vert_back_porch
set_parameter_property vert_back_porch TYPE INTEGER
set_parameter_property vert_back_porch UNITS None
set_parameter_property vert_back_porch ALLOWED_RANGES -2147483648:2147483647
set_parameter_property vert_back_porch DESCRIPTION ""
set_parameter_property vert_back_porch HDL_PARAMETER true
add_parameter vert_pix INTEGER 600 ""
set_parameter_property vert_pix DEFAULT_VALUE 600
set_parameter_property vert_pix DISPLAY_NAME vert_pix
set_parameter_property vert_pix TYPE INTEGER
set_parameter_property vert_pix UNITS None
set_parameter_property vert_pix ALLOWED_RANGES -2147483648:2147483647
set_parameter_property vert_pix DESCRIPTION ""
set_parameter_property vert_pix HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 80000000
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_sink
# 
add_interface avalon_sink avalon_streaming end
set_interface_property avalon_sink associatedClock clock
set_interface_property avalon_sink associatedReset reset
set_interface_property avalon_sink dataBitsPerSymbol 24
set_interface_property avalon_sink errorDescriptor ""
set_interface_property avalon_sink firstSymbolInHighOrderBits true
set_interface_property avalon_sink maxChannel 0
set_interface_property avalon_sink readyLatency 0
set_interface_property avalon_sink ENABLED true
set_interface_property avalon_sink EXPORT_OF ""
set_interface_property avalon_sink PORT_NAME_MAP ""
set_interface_property avalon_sink CMSIS_SVD_VARIABLES ""
set_interface_property avalon_sink SVD_ADDRESS_GROUP ""

add_interface_port avalon_sink data data Input 24
add_interface_port avalon_sink ready ready Output 1
add_interface_port avalon_sink valid valid Input 1


# 
# connection point hdmi_1
# 
add_interface hdmi_1 conduit end
set_interface_property hdmi_1 associatedClock clock
set_interface_property hdmi_1 associatedReset ""
set_interface_property hdmi_1 ENABLED true
set_interface_property hdmi_1 EXPORT_OF ""
set_interface_property hdmi_1 PORT_NAME_MAP ""
set_interface_property hdmi_1 CMSIS_SVD_VARIABLES ""
set_interface_property hdmi_1 SVD_ADDRESS_GROUP ""

add_interface_port hdmi_1 blue_n blue_n Output 1
add_interface_port hdmi_1 blue_p blue_p Output 1
add_interface_port hdmi_1 clk_pix_n clk_pix_n Output 1
add_interface_port hdmi_1 clk_pix_p clk_pix_p Output 1
add_interface_port hdmi_1 green_n green_n Output 1
add_interface_port hdmi_1 green_p green_p Output 1
add_interface_port hdmi_1 red_n red_n Output 1
add_interface_port hdmi_1 red_p red_p Output 1
add_interface_port hdmi_1 x x Output 11
add_interface_port hdmi_1 y y Output 11
add_interface_port hdmi_1 horz horz Output 11
add_interface_port hdmi_1 vert vert Output 11
add_interface_port hdmi_1 clk_st clk_st Output 1


# 
# connection point clk_pix
# 
add_interface clk_pix clock end
set_interface_property clk_pix clockRate 80000000
set_interface_property clk_pix ENABLED true
set_interface_property clk_pix EXPORT_OF ""
set_interface_property clk_pix PORT_NAME_MAP ""
set_interface_property clk_pix CMSIS_SVD_VARIABLES ""
set_interface_property clk_pix SVD_ADDRESS_GROUP ""

add_interface_port clk_pix clk_pix clk Input 1


# 
# connection point clk_x10
# 
add_interface clk_x10 clock end
set_interface_property clk_x10 clockRate 400000000
set_interface_property clk_x10 ENABLED true
set_interface_property clk_x10 EXPORT_OF ""
set_interface_property clk_x10 PORT_NAME_MAP ""
set_interface_property clk_x10 CMSIS_SVD_VARIABLES ""
set_interface_property clk_x10 SVD_ADDRESS_GROUP ""

add_interface_port clk_x10 clk_x10 clk Input 1

