# TCL File Generated by Component Editor 18.0
# Mon Dec 11 14:42:33 MSK 2023
# DO NOT MODIFY


# 
# hdmi_mm "hdmi_mm" v1.0
#  2023.12.11.14:42:33
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module hdmi_mm
# 
set_module_property DESCRIPTION ""
set_module_property NAME hdmi_mm
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME hdmi_mm
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL hdmi_mm
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file hdmi_mm.sv SYSTEM_VERILOG PATH hdmi_mm.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter horz_front_porch INTEGER 18
set_parameter_property horz_front_porch DEFAULT_VALUE 18
set_parameter_property horz_front_porch DISPLAY_NAME horz_front_porch
set_parameter_property horz_front_porch TYPE INTEGER
set_parameter_property horz_front_porch UNITS None
set_parameter_property horz_front_porch ALLOWED_RANGES -2147483648:2147483647
set_parameter_property horz_front_porch HDL_PARAMETER true
add_parameter horz_sync INTEGER 60
set_parameter_property horz_sync DEFAULT_VALUE 60
set_parameter_property horz_sync DISPLAY_NAME horz_sync
set_parameter_property horz_sync TYPE INTEGER
set_parameter_property horz_sync UNITS None
set_parameter_property horz_sync ALLOWED_RANGES -2147483648:2147483647
set_parameter_property horz_sync HDL_PARAMETER true
add_parameter horz_back_porch INTEGER 112
set_parameter_property horz_back_porch DEFAULT_VALUE 112
set_parameter_property horz_back_porch DISPLAY_NAME horz_back_porch
set_parameter_property horz_back_porch TYPE INTEGER
set_parameter_property horz_back_porch UNITS None
set_parameter_property horz_back_porch ALLOWED_RANGES -2147483648:2147483647
set_parameter_property horz_back_porch HDL_PARAMETER true
add_parameter horz_pix INTEGER 1024
set_parameter_property horz_pix DEFAULT_VALUE 1024
set_parameter_property horz_pix DISPLAY_NAME horz_pix
set_parameter_property horz_pix TYPE INTEGER
set_parameter_property horz_pix UNITS None
set_parameter_property horz_pix ALLOWED_RANGES -2147483648:2147483647
set_parameter_property horz_pix HDL_PARAMETER true
add_parameter vert_front_porch INTEGER 18
set_parameter_property vert_front_porch DEFAULT_VALUE 18
set_parameter_property vert_front_porch DISPLAY_NAME vert_front_porch
set_parameter_property vert_front_porch TYPE INTEGER
set_parameter_property vert_front_porch UNITS None
set_parameter_property vert_front_porch ALLOWED_RANGES -2147483648:2147483647
set_parameter_property vert_front_porch HDL_PARAMETER true
add_parameter vert_sync INTEGER 60
set_parameter_property vert_sync DEFAULT_VALUE 60
set_parameter_property vert_sync DISPLAY_NAME vert_sync
set_parameter_property vert_sync TYPE INTEGER
set_parameter_property vert_sync UNITS None
set_parameter_property vert_sync ALLOWED_RANGES -2147483648:2147483647
set_parameter_property vert_sync HDL_PARAMETER true
add_parameter vert_back_porch INTEGER 112
set_parameter_property vert_back_porch DEFAULT_VALUE 112
set_parameter_property vert_back_porch DISPLAY_NAME vert_back_porch
set_parameter_property vert_back_porch TYPE INTEGER
set_parameter_property vert_back_porch UNITS None
set_parameter_property vert_back_porch ALLOWED_RANGES -2147483648:2147483647
set_parameter_property vert_back_porch HDL_PARAMETER true
add_parameter vert_pix INTEGER 600
set_parameter_property vert_pix DEFAULT_VALUE 600
set_parameter_property vert_pix DISPLAY_NAME vert_pix
set_parameter_property vert_pix TYPE INTEGER
set_parameter_property vert_pix UNITS None
set_parameter_property vert_pix ALLOWED_RANGES -2147483648:2147483647
set_parameter_property vert_pix HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 80000000
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point hdmi_mm
# 
add_interface hdmi_mm conduit end
set_interface_property hdmi_mm associatedClock clock
set_interface_property hdmi_mm associatedReset reset
set_interface_property hdmi_mm ENABLED true
set_interface_property hdmi_mm EXPORT_OF ""
set_interface_property hdmi_mm PORT_NAME_MAP ""
set_interface_property hdmi_mm CMSIS_SVD_VARIABLES ""
set_interface_property hdmi_mm SVD_ADDRESS_GROUP ""

add_interface_port hdmi_mm clk_mm clk_mm Output 1
add_interface_port hdmi_mm clk_pix_p clk_pix_p Output 1
add_interface_port hdmi_mm clk_pix_n clk_pix_n Output 1
add_interface_port hdmi_mm red_p red_p Output 1
add_interface_port hdmi_mm red_n red_n Output 1
add_interface_port hdmi_mm green_p green_p Output 1
add_interface_port hdmi_mm green_n green_n Output 1
add_interface_port hdmi_mm blue_p blue_p Output 1
add_interface_port hdmi_mm blue_n blue_n Output 1
add_interface_port hdmi_mm x x Output 11
add_interface_port hdmi_mm y y Output 11
add_interface_port hdmi_mm horz horz Output 11
add_interface_port hdmi_mm vert vert Output 11


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 1
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave s_read read Input 1
add_interface_port avalon_slave s_write write Input 1
add_interface_port avalon_slave s_address address Input 10
add_interface_port avalon_slave s_writedata writedata Input 32
add_interface_port avalon_slave s_burstcount burstcount Input 1
add_interface_port avalon_slave s_byteenable byteenable Input 4
add_interface_port avalon_slave s_waitrequest waitrequest Output 1
add_interface_port avalon_slave s_readdatavalid readdatavalid Output 1
add_interface_port avalon_slave s_readdata readdata Output 32
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clk_x10
# 
add_interface clk_x10 clock end
set_interface_property clk_x10 clockRate 400000000
set_interface_property clk_x10 ENABLED true
set_interface_property clk_x10 EXPORT_OF ""
set_interface_property clk_x10 PORT_NAME_MAP ""
set_interface_property clk_x10 CMSIS_SVD_VARIABLES ""
set_interface_property clk_x10 SVD_ADDRESS_GROUP ""

add_interface_port clk_x10 clk_x10 clk Input 1

