# TCL File Generated by Component Editor 18.0
# Wed Jul 26 14:05:35 MSK 2023
# DO NOT MODIFY


# 
# hdmi_avl "hdmi_avl" v1.0
#  2023.07.26.14:05:35
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module hdmi_avl
# 
set_module_property DESCRIPTION ""
set_module_property NAME hdmi_avl
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME hdmi_avl
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL hdmi
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file hdmi.sv SYSTEM_VERILOG PATH hdmi.sv TOP_LEVEL_FILE
add_fileset_file tmds_encoder.sv SYSTEM_VERILOG PATH tmds_encoder.sv
add_fileset_file tmds_serial.sv SYSTEM_VERILOG PATH tmds_serial.sv

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL hdmi
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file hdmi.sv SYSTEM_VERILOG PATH hdmi.sv
add_fileset_file tmds_encoder.sv SYSTEM_VERILOG PATH tmds_encoder.sv
add_fileset_file tmds_serial.sv SYSTEM_VERILOG PATH tmds_serial.sv


# 
# parameters
# 
add_parameter horz_front_porch INTEGER 20 ""
set_parameter_property horz_front_porch DEFAULT_VALUE 20
set_parameter_property horz_front_porch DISPLAY_NAME horz_front_porch
set_parameter_property horz_front_porch TYPE INTEGER
set_parameter_property horz_front_porch UNITS None
set_parameter_property horz_front_porch ALLOWED_RANGES -2147483648:2147483647
set_parameter_property horz_front_porch DESCRIPTION ""
set_parameter_property horz_front_porch HDL_PARAMETER true
add_parameter horz_sync INTEGER 60 ""
set_parameter_property horz_sync DEFAULT_VALUE 60
set_parameter_property horz_sync DISPLAY_NAME horz_sync
set_parameter_property horz_sync TYPE INTEGER
set_parameter_property horz_sync UNITS None
set_parameter_property horz_sync ALLOWED_RANGES -2147483648:2147483647
set_parameter_property horz_sync DESCRIPTION ""
set_parameter_property horz_sync HDL_PARAMETER true
add_parameter horz_back_porch INTEGER 110 ""
set_parameter_property horz_back_porch DEFAULT_VALUE 110
set_parameter_property horz_back_porch DISPLAY_NAME horz_back_porch
set_parameter_property horz_back_porch TYPE INTEGER
set_parameter_property horz_back_porch UNITS None
set_parameter_property horz_back_porch ALLOWED_RANGES -2147483648:2147483647
set_parameter_property horz_back_porch DESCRIPTION ""
set_parameter_property horz_back_porch HDL_PARAMETER true
add_parameter horz_pix INTEGER 1024 ""
set_parameter_property horz_pix DEFAULT_VALUE 1024
set_parameter_property horz_pix DISPLAY_NAME horz_pix
set_parameter_property horz_pix TYPE INTEGER
set_parameter_property horz_pix UNITS None
set_parameter_property horz_pix ALLOWED_RANGES -2147483648:2147483647
set_parameter_property horz_pix DESCRIPTION ""
set_parameter_property horz_pix HDL_PARAMETER true
add_parameter vert_front_porch INTEGER 30 ""
set_parameter_property vert_front_porch DEFAULT_VALUE 30
set_parameter_property vert_front_porch DISPLAY_NAME vert_front_porch
set_parameter_property vert_front_porch TYPE INTEGER
set_parameter_property vert_front_porch UNITS None
set_parameter_property vert_front_porch ALLOWED_RANGES -2147483648:2147483647
set_parameter_property vert_front_porch DESCRIPTION ""
set_parameter_property vert_front_porch HDL_PARAMETER true
add_parameter vert_sync INTEGER 80 ""
set_parameter_property vert_sync DEFAULT_VALUE 80
set_parameter_property vert_sync DISPLAY_NAME vert_sync
set_parameter_property vert_sync TYPE INTEGER
set_parameter_property vert_sync UNITS None
set_parameter_property vert_sync ALLOWED_RANGES -2147483648:2147483647
set_parameter_property vert_sync DESCRIPTION ""
set_parameter_property vert_sync HDL_PARAMETER true
add_parameter vert_back_porch INTEGER 110 ""
set_parameter_property vert_back_porch DEFAULT_VALUE 110
set_parameter_property vert_back_porch DISPLAY_NAME vert_back_porch
set_parameter_property vert_back_porch TYPE INTEGER
set_parameter_property vert_back_porch UNITS None
set_parameter_property vert_back_porch ALLOWED_RANGES -2147483648:2147483647
set_parameter_property vert_back_porch DESCRIPTION ""
set_parameter_property vert_back_porch HDL_PARAMETER true
add_parameter vert_pix INTEGER 600 ""
set_parameter_property vert_pix DEFAULT_VALUE 600
set_parameter_property vert_pix DISPLAY_NAME vert_pix
set_parameter_property vert_pix TYPE INTEGER
set_parameter_property vert_pix UNITS None
set_parameter_property vert_pix ALLOWED_RANGES -2147483648:2147483647
set_parameter_property vert_pix DESCRIPTION ""
set_parameter_property vert_pix HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point hdmi
# 
add_interface hdmi conduit end
set_interface_property hdmi associatedClock clock
set_interface_property hdmi associatedReset reset
set_interface_property hdmi ENABLED true
set_interface_property hdmi EXPORT_OF ""
set_interface_property hdmi PORT_NAME_MAP ""
set_interface_property hdmi CMSIS_SVD_VARIABLES ""
set_interface_property hdmi SVD_ADDRESS_GROUP ""

add_interface_port hdmi clk_pix_p clk_pix_p Output 1
add_interface_port hdmi clk_pix_n clk_pix_n Output 1
add_interface_port hdmi red_p red_p Output 1
add_interface_port hdmi red_n red_n Output 1
add_interface_port hdmi green_p green_p Output 1
add_interface_port hdmi green_n green_n Output 1
add_interface_port hdmi blue_p blue_p Output 1
add_interface_port hdmi blue_n blue_n Output 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitStates 32
set_interface_property avalon_slave readWaitTime 32
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave s_address address Input 12
add_interface_port avalon_slave s_write write Input 1
add_interface_port avalon_slave s_writedata writedata Input 32
add_interface_port avalon_slave s_chipselect chipselect Input 1
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits WORDS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 4
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master m_read read Output 1
add_interface_port avalon_master m_write write Output 1
add_interface_port avalon_master m_address address Output 30
add_interface_port avalon_master m_writedata writedata Output 32
add_interface_port avalon_master m_readdata readdata Input 32
add_interface_port avalon_master m_readdatavalid readdatavalid Input 1
add_interface_port avalon_master m_byteenable byteenable Output 4
add_interface_port avalon_master m_burstcount burstcount Output 11
add_interface_port avalon_master m_waitrequest waitrequest Input 1


# 
# connection point x10_clock
# 
add_interface x10_clock clock end
set_interface_property x10_clock clockRate 0
set_interface_property x10_clock ENABLED true
set_interface_property x10_clock EXPORT_OF ""
set_interface_property x10_clock PORT_NAME_MAP ""
set_interface_property x10_clock CMSIS_SVD_VARIABLES ""
set_interface_property x10_clock SVD_ADDRESS_GROUP ""

add_interface_port x10_clock clk_x10 clk Input 1


# 
# connection point pix_clock
# 
add_interface pix_clock clock end
set_interface_property pix_clock clockRate 0
set_interface_property pix_clock ENABLED true
set_interface_property pix_clock EXPORT_OF ""
set_interface_property pix_clock PORT_NAME_MAP ""
set_interface_property pix_clock CMSIS_SVD_VARIABLES ""
set_interface_property pix_clock SVD_ADDRESS_GROUP ""

add_interface_port pix_clock clk_pix clk Input 1

